FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .
RUN dotnet restore ./1-Services/ModernizationPlatform.Worker/ModernizationPlatform.Worker.csproj
RUN dotnet publish ./1-Services/ModernizationPlatform.Worker/ModernizationPlatform.Worker.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

RUN apt-get update \
	&& apt-get install -y --no-install-recommends git \
	&& rm -rf /var/lib/apt/lists/*

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "ModernizationPlatform.Worker.dll"]
