// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernizationPlatform.Infra.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModernizationPlatform.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206005207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.AnalysisJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<string>("OutputJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("output");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("analysis_type");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_analysis_jobs_request_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_analysis_jobs_status");

                    b.ToTable("analysis_jobs", (string)null);
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.AnalysisRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("repository_url");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("SelectedTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_types");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_analysis_requests_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_analysis_requests_status");

                    b.ToTable("analysis_requests", (string)null);
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("file_path");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_findings_job_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_findings_severity");

                    b.ToTable("findings", (string)null);
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.Prompt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("analysis_type");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisType")
                        .IsUnique()
                        .HasDatabaseName("IX_prompts_analysis_type");

                    b.ToTable("prompts", (string)null);
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("LastAnalysisAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analysis_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("IX_repositories_url");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.SharedContext", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dependencies")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("dependencies");

                    b.Property<string>("DirectoryStructureJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("directory_structure");

                    b.Property<string>("Frameworks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("frameworks");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("languages");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("RequestId")
                        .HasDatabaseName("IX_shared_contexts_request_id");

                    b.ToTable("shared_contexts", (string)null);
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.AnalysisJob", b =>
                {
                    b.HasOne("ModernizationPlatform.Domain.Entities.AnalysisRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_analysis_jobs_analysis_requests");
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.Finding", b =>
                {
                    b.HasOne("ModernizationPlatform.Domain.Entities.AnalysisJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_findings_analysis_jobs");
                });

            modelBuilder.Entity("ModernizationPlatform.Domain.Entities.SharedContext", b =>
                {
                    b.HasOne("ModernizationPlatform.Domain.Entities.AnalysisRequest", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_shared_contexts_analysis_requests");
                });
#pragma warning restore 612, 618
        }
    }
}
